export const SET_AUTH_STATUS = "SET_AUTH_STATUS"
export const SET_AUTH_USER = "SET_AUTH_USER"
export const SET_CURR_USER_DATA = "SET_CURR_USER_DATA"
export const SET_USER_GROUPS = "SET_USER_GROUPS"
export const SET_SOCKET = "SET_SOCKET";
