export const ADD_FRIEND = "ADD_FRIEND"
export const REMOVE_FRIEND = "REMOVE_FRIEND"
export const SET_FRIENDS = "SET_FRIENDS"
export const SET_OTHER_FRIENDS = "SET_OTHER_FRIENDS"

export const SET_CUR_PROFILE = "SET_CUR_PROFILE"

export const LOAD_USERS = "LOAD_USERS"
