export const ADD_FRIEND = "ADD_FRIEND"
export const REMOVE_FRIEND = "REMOVE_FRIEND"
export const SET_FRIENDS = "SET_FRIENDs"
export const SET_CUR_PROFILE = "SET_CUR_PROFILE"
export const SET_OTHER_FRIENDS = "SET_OTHER_FRIENDS"
export const UPDATE_FRIEND = "UPDATE_FRIEND"

export const LOAD_USERS = "LOAD_USERS"
