export const NOTIFICATIONS_PAGE = "NOTIFICATIONS_PAGE"
export const TEMP_GROUPS_PAGE = "TEMP_GROUPS_PAGE"
export const PERM_GROUPS_PAGE = "PERM_GROUPS_PAGE"
export const PROFILE_PAGE = "PROFILE_PAGE"
