//All navigator screen names

//Authentication
export const SIGN_IN_PAGE = "SIGN_IN_PAGE"
export const SIGN_UP_PAGE = "SIGN_UP_PAGE"
export const CONFIRM_SIGN_UP_PAGE = "CONFIRM_SIGN_UP_PAGE"
export const FORGOT_PASSWORD_PAGE = "FORGOT_PASSWORD_PAGE"

//Tab Navigator
export const NOTIFICATIONS_PAGE = "NOTIFICATIONS_PAGE"
export const EVENTS_PAGE = "EVENTS_PAGE"
export const GROUPS_PAGE = "GROUPS_PAGE"
export const PROFILE_PAGE = "PROFILE_PAGE"

//Notifications
export const NOTIFICATIONS_VIEW = "NOTIFICATIONS_VIEW"
export const NOTIFICATIONS_PROFILE = "NOTIFICATIONS_PROFILE"

//Events
export const EVENTS_VIEW = "EVENTS_VIEW"
export const EVENTS_SINGLE_EVENT = "EVENTS_SINGLE_EVENT"
export const EVENTS_CREATE_EVENT = "EVENTS_CREATE_EVENT"
export const EVENTS_MEMBERS = "EVENTS_MEMBERS"
export const EVENTS_ADD_MEMBERS = "EVENTS_ADD_MEMBERS"
export const EVENTS_PROFILE = "EVENTS_PROFILE"
export const EVENTS_EDIT_EVENT = "EVENTS_EDIT_EVENT"
export const EVENTS_CHAT = "EVENTS_CHAT"
export const EVENTS_POTENTIAL_LOCATION = "EVENTS_POTENTIAL_LOCATION"
export const EVENTS_LOCATION_SELECT = "EVENTS_LOCATION_SELECT"
//Event matches
export const EVENTS_SINGLE_MATCH = "EVENTS_SINGLE_MATCH"
export const EVENTS_MATCH_CHAT = "EVENTS_MATCH_CHAT"
export const EVENTS_MERGING = "EVENTS_MERGING"
//Events Find New Matches
export const EVENTS_SEARCH_MATCHES = "EVENTS_SEARCH_MATCHES"
export const EVENTS_POTENTIAL_MATCH = "EVENTS_POTENTIAL_MATCH"

//Groups
export const GROUPS_VIEW = "GROUPS_VIEW"
export const GROUPS_CREATE_EVENT = "GROUPS_CREATE_EVENT"
export const GROUPS_CREATE_GROUP = "GROUPS_CREATE_GROUP"
export const GROUPS_SINGLE_GROUP = "GROUPS_SINGLE_GROUP"
export const GROUPS_CHAT = "GROUPS_CHAT"
export const GROUPS_MEMBERS = "GROUPS_MEMBERS"
export const GROUPS_EDIT_GROUP = "GROUPS_EDIT_GROUP"
export const GROUPS_ADD_MEMBERS = "GROUPS_ADD_MEMBERS"
export const GROUPS_PROFILE = "GROUPS_PROFILE"
//Profile
export const PROFILE_VIEW = "PROFILE_VIEW"
export const PROFILE_EDIT_PROFILE = "PROFILE_EDIT_PROFILE"
export const PROFILE_CONFIRM_EMAIL = "PROFILE_CONFIRM_EMAIL"
export const PROFILE_FRIENDS = "PROFILE_FRIENDS"
export const PROFILE_PROFILE = "PROFILE_PROFILE"
export const PROFILE_SEARCH_FRIENDS = "PROFILE_SEARCH_FRIENDS"
