export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  PAGE_BACKGROUND_COLOR: "444",
  LIST_ITEM_COLOR: "#DDD",
  LIST_ITEM_BORDER_COLOR: "#555",
  PRIMARY_COLOR: "#33D",
  SECONDARY_COLOR: "#DDD",
}
